import type { TBCanvas, TBNode } from '@terrabuilder/engine';
import { resolveGraph, sanitizeName } from '@terrabuilder/engine';
import { getSchema } from '@terrabuilder/schemas';

// ─── CloudFormation Emitter ───────────────────────────────────────────────────
// Generates AWS CloudFormation YAML from a TBCanvas IR.

export function emitCloudFormation(canvas: TBCanvas): string {
  const awsNodes = canvas.nodes.filter(n => n.data.provider === 'aws');
  const nonAwsNodes = canvas.nodes.filter(n => n.data.provider !== 'aws');

  if (canvas.nodes.length === 0) {
    return `# TerraBuilder — CloudFormation\n# Add AWS resources to generate CloudFormation templates.\n`;
  }

  const sections: string[] = [];
  sections.push(
    `# TerraBuilder Generated CloudFormation Template
# Canvas: ${canvas.meta.name}
# Generated: ${new Date().toISOString()}
AWSTemplateFormatVersion: '2010-09-09'
Description: '${canvas.meta.name} — Generated by TerraBuilder'
`
  );

  if (nonAwsNodes.length > 0) {
    sections.push(
      `# NOTE: ${nonAwsNodes.length} non-AWS resource(s) omitted from CloudFormation output.\n# Use Terraform or Bicep output for multi-cloud deployments.\n`
    );
  }

  if (awsNodes.length === 0) {
    sections.push('# No AWS resources found in this canvas.');
    return sections.join('\n');
  }

  sections.push('Parameters:');
  sections.push('  Environment:');
  sections.push('    Type: String');
  sections.push("    Default: production");
  sections.push("    AllowedValues: [production, staging, development]");
  sections.push('');

  const { order } = resolveGraph({ nodes: awsNodes, edges: canvas.edges, meta: canvas.meta });
  const nodeMap = new Map(awsNodes.map(n => [n.id, n]));

  sections.push('Resources:');

  for (const nodeId of order) {
    const node = nodeMap.get(nodeId);
    if (!node) continue;
    const schema = getSchema(node.data.resourceType);
    const cfnType = schema?.cfnType;
    if (!cfnType) continue;

    const logicalId = toCfnLogicalId(node.data.displayName);
    sections.push(`  ${logicalId}:`);
    sections.push(`    Type: ${cfnType}`);
    sections.push('    Properties:');

    const props = buildCfnProperties(node, canvas);
    for (const [k, v] of Object.entries(props)) {
      sections.push(`      ${k}: ${formatCfnValue(v)}`);
    }

    sections.push(`    Metadata:`);
    sections.push(`      TerraBuilder:`);
    sections.push(`        ResourceId: ${node.id}`);
    sections.push(`        SecurityScore: ${node.data.securityScore}`);
    sections.push('');
  }

  sections.push('Outputs:');
  for (const nodeId of order) {
    const node = nodeMap.get(nodeId);
    if (!node) continue;
    const schema = getSchema(node.data.resourceType);
    if (!schema?.cfnType) continue;
    const logicalId = toCfnLogicalId(node.data.displayName);
    sections.push(`  ${logicalId}Id:`);
    sections.push(`    Description: ID of ${node.data.displayName}`);
    sections.push(`    Value: !Ref ${logicalId}`);
    sections.push(`    Export:`);
    sections.push(`      Name: !Sub '\${AWS::StackName}-${logicalId}'`);
  }

  return sections.join('\n');
}

function toCfnLogicalId(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]/)
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function formatCfnValue(value: unknown): string {
  if (typeof value === 'string') return value.includes(' ') ? `"${value}"` : value;
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return String(value);
  return JSON.stringify(value);
}

function buildCfnProperties(node: TBNode, canvas: TBCanvas): Record<string, unknown> {
  const config = node.data.config;
  const props: Record<string, unknown> = {};

  // Map common Terraform properties to CFN equivalents
  const cfnMappings: Record<string, string> = {
    ami: 'ImageId',
    instance_type: 'InstanceType',
    key_name: 'KeyName',
    bucket: 'BucketName',
    engine: 'Engine',
    engine_version: 'EngineVersion',
    instance_class: 'DBInstanceClass',
    db_name: 'DBName',
    username: 'MasterUsername',
    allocated_storage: 'AllocatedStorage',
    multi_az: 'MultiAZ',
    publicly_accessible: 'PubliclyAccessible',
    storage_encrypted: 'StorageEncrypted',
    backup_retention_period: 'BackupRetentionPeriod',
    deletion_protection: 'DeletionProtection',
    function_name: 'FunctionName',
    runtime: 'Runtime',
    handler: 'Handler',
    timeout: 'Timeout',
    memory_size: 'MemorySize',
  };

  for (const [tfKey, cfnKey] of Object.entries(cfnMappings)) {
    if (config[tfKey] !== undefined && config[tfKey] !== null) {
      props[cfnKey] = config[tfKey];
    }
  }

  // Add standard tags
  props['Tags'] = [
    { Key: 'Name', Value: node.data.displayName },
    { Key: 'ManagedBy', Value: 'TerraBuilder' },
  ];

  return props;
}
