import type { TBCanvas, OutputFormat } from '@terrabuilder/engine';
import { emitTerraform } from './terraform.js';
import { emitCloudFormation } from './cloudformation.js';
import { emitBicep } from './bicep.js';
import { emitPulumi } from './pulumi.js';

export interface ProjectFile {
  filename: string;
  content: string;
}

export function generateProjectBundle(canvas: TBCanvas, format: OutputFormat): ProjectFile[] {
  const files: ProjectFile[] = [];

  if (format === 'terraform') {
    const mainCode = emitTerraform(canvas);
    files.push({
      filename: 'main.tf',
      content: mainCode,
    });
    files.push({
      filename: 'variables.tf',
      content: `variable "aws_region" {\n  description = "AWS Region"\n  type        = string\n  default     = "us-east-1"\n}\n`,
    });
    files.push({
      filename: 'outputs.tf',
      content: `# TerraBuilder Generated Outputs\n`,
    });
    files.push({
      filename: '.github/workflows/terraform-ci.yml',
      content: `name: "Terraform CI"

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: "Terraform Plan & Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
`,
    });
  } else if (format === 'cloudformation') {
    files.push({
      filename: 'template.yaml',
      content: emitCloudFormation(canvas),
    });
  } else if (format === 'bicep') {
    files.push({
      filename: 'main.bicep',
      content: emitBicep(canvas),
    });
  } else if (format === 'pulumi') {
    files.push({
      filename: 'index.ts',
      content: emitPulumi(canvas),
    });
    files.push({
      filename: 'Pulumi.yaml',
      content: `name: terrabuilder-stack\nruntime: nodejs\ndescription: Generated by TerraBuilder\n`,
    });
    files.push({
      filename: 'package.json',
      content: JSON.stringify({
        name: "terrabuilder-stack",
        main: "index.ts",
        dependencies: {
          "@pulumi/pulumi": "^3.0.0",
          "@pulumi/aws": "^6.0.0",
          "@pulumi/azure-native": "^2.0.0",
          "@pulumi/gcp": "^7.0.0"
        }
      }, null, 2),
    });
  }

  // Include visual canvas project file
  files.push({
    filename: 'terrabuilder-architecture.tbp',
    content: JSON.stringify(canvas, null, 2),
  });

  files.push({
    filename: 'README.md',
    content: `# TerraBuilder Infrastructure Project

This infrastructure stack was visually designed and compiled with **TerraBuilder v0.2.0**.

## Deployment Instructions

### Format: ${format.toUpperCase()}

1. Review the generated files in this directory.
2. Run standard IaC deployment commands (e.g. \`terraform init && terraform apply\` or \`pulumi up\`).
3. Re-import \`terrabuilder-architecture.tbp\` into TerraBuilder anytime to visually update this stack.
`,
  });

  return files;
}
