import type { ResourceSchema } from '../types.js';

// ─── AWS Resource Schemas ─────────────────────────────────────────────────────
// 22 AWS resources for Phase 1

const AWS_ORANGE = '#e8420a';
const AWS_BG = 'rgba(232,66,10,0.08)';

export const awsSchemas: ResourceSchema[] = [
  // ─── EC2 Instance ──────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_instance',
    cfnType: 'AWS::EC2::Instance',
    displayName: 'EC2 Instance',
    friendlyName: 'Server',
    description: 'A virtual server in the cloud. Run applications, websites, or workloads.',
    icon: '🖥️',
    color: AWS_ORANGE,
    bgColor: AWS_BG,
    category: 'Compute',
    tags: ['compute', 'server', 'virtual machine', 'ec2'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_security_group', relationship: 'vpc_security_group_ids' },
      { targetResourceType: 'aws_subnet', relationship: 'subnet_id' },
      { targetResourceType: 'aws_iam_role', relationship: 'iam_instance_profile' },
    ],
    canReceiveFrom: ['aws_subnet', 'aws_security_group', 'aws_iam_role', 'aws_alb'],
    secureDefaults: {
      monitoring: true,
      root_block_device_encrypted: true,
      metadata_options_http_tokens: 'required',
      associate_public_ip_address: false,
    },
    properties: [
      { key: 'ami', label: 'AMI ID', friendlyLabel: 'Operating System Image', type: 'string', required: true, default: 'ami-0c55b159cbfafe1f0', placeholder: 'ami-xxxxxxxxxxxxxxxxx', showInBeginner: true },
      { key: 'instance_type', label: 'Instance Type', friendlyLabel: 'Server Size', type: 'select', required: true, default: 't3.micro', showInBeginner: true, options: [
        { label: 't3.micro (1 vCPU, 1GB RAM) — Free Tier', value: 't3.micro' },
        { label: 't3.small (2 vCPU, 2GB RAM)', value: 't3.small' },
        { label: 't3.medium (2 vCPU, 4GB RAM)', value: 't3.medium' },
        { label: 't3.large (2 vCPU, 8GB RAM)', value: 't3.large' },
        { label: 't3.xlarge (4 vCPU, 16GB RAM)', value: 't3.xlarge' },
        { label: 'm5.large (2 vCPU, 8GB RAM)', value: 'm5.large' },
        { label: 'm5.xlarge (4 vCPU, 16GB RAM)', value: 'm5.xlarge' },
        { label: 'c5.xlarge (4 vCPU, 8GB RAM) — Compute Optimized', value: 'c5.xlarge' },
      ]},
      { key: 'key_name', label: 'Key Pair Name', friendlyLabel: 'SSH Key', type: 'string', required: false, placeholder: 'my-keypair' },
      { key: 'monitoring', label: 'Detailed Monitoring', friendlyLabel: 'Enable Monitoring', type: 'boolean', required: false, default: true },
      { key: 'associate_public_ip_address', label: 'Public IP Address', friendlyLabel: 'Make Publicly Accessible', type: 'boolean', required: false, default: false, showInBeginner: true },
      { key: 'root_block_device_encrypted', label: 'Encrypt Root Volume', friendlyLabel: 'Encrypt Disk', type: 'boolean', required: false, default: true, showInBeginner: true },
      { key: 'tags_Name', label: 'Name Tag', friendlyLabel: 'Server Name', type: 'string', required: false, showInBeginner: true },
    ],
  },

  // ─── S3 Bucket ─────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_s3_bucket',
    cfnType: 'AWS::S3::Bucket',
    displayName: 'S3 Bucket',
    friendlyName: 'File Storage',
    description: 'Object storage for files, images, backups, and static websites.',
    icon: '🪣',
    color: '#2196f3',
    bgColor: 'rgba(33,150,243,0.08)',
    category: 'Storage',
    tags: ['storage', 'object storage', 'files', 's3', 'bucket'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_cloudfront_distribution', relationship: 'origin_domain_name' },
    ],
    canReceiveFrom: ['aws_cloudfront_distribution', 'aws_iam_role', 'aws_lambda_function'],
    secureDefaults: {
      versioning_enabled: true,
      sse_algorithm: 'AES256',
      block_public_acls: true,
      block_public_policy: true,
      ignore_public_acls: true,
      restrict_public_buckets: true,
    },
    properties: [
      { key: 'bucket', label: 'Bucket Name', friendlyLabel: 'Storage Name', type: 'string', required: false, placeholder: 'my-unique-bucket-name', showInBeginner: true },
      { key: 'versioning_enabled', label: 'Versioning', friendlyLabel: 'Keep Old Versions of Files', type: 'boolean', required: false, default: true, showInBeginner: true },
      { key: 'block_public_acls', label: 'Block Public ACLs', friendlyLabel: 'Block Public Access', type: 'boolean', required: false, default: true, showInBeginner: true },
      { key: 'block_public_policy', label: 'Block Public Policy', friendlyLabel: 'Block Public Policy', type: 'boolean', required: false, default: true },
      { key: 'ignore_public_acls', label: 'Ignore Public ACLs', friendlyLabel: 'Ignore Public ACLs', type: 'boolean', required: false, default: true },
      { key: 'restrict_public_buckets', label: 'Restrict Public Buckets', friendlyLabel: 'Restrict Public Access', type: 'boolean', required: false, default: true },
      { key: 'sse_algorithm', label: 'Encryption Algorithm', friendlyLabel: 'Encryption Type', type: 'select', required: false, default: 'AES256', options: [
        { label: 'AES-256 (Server-Side)', value: 'AES256' },
        { label: 'AWS KMS (Managed Keys)', value: 'aws:kms' },
      ]},
      { key: 'force_destroy', label: 'Force Destroy', friendlyLabel: 'Allow Deletion', type: 'boolean', required: false, default: false },
    ],
  },

  // ─── VPC ───────────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_vpc',
    cfnType: 'AWS::EC2::VPC',
    displayName: 'VPC',
    friendlyName: 'Private Network',
    description: 'Virtual Private Cloud — an isolated network for your AWS resources.',
    icon: '🌐',
    color: '#9c27b0',
    bgColor: 'rgba(156,39,176,0.08)',
    category: 'Network',
    tags: ['network', 'vpc', 'virtual private cloud', 'networking'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_subnet', relationship: 'vpc_id' },
      { targetResourceType: 'aws_security_group', relationship: 'vpc_id' },
      { targetResourceType: 'aws_internet_gateway', relationship: 'vpc_id' },
    ],
    canReceiveFrom: [],
    secureDefaults: {
      enable_dns_support: true,
      enable_dns_hostnames: true,
    },
    properties: [
      { key: 'cidr_block', label: 'CIDR Block', friendlyLabel: 'Network Address Range', type: 'cidr', required: true, default: '10.0.0.0/16', showInBeginner: true },
      { key: 'enable_dns_support', label: 'DNS Support', friendlyLabel: 'Enable DNS', type: 'boolean', required: false, default: true },
      { key: 'enable_dns_hostnames', label: 'DNS Hostnames', friendlyLabel: 'Enable DNS Names', type: 'boolean', required: false, default: true },
    ],
  },

  // ─── Subnet ────────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_subnet',
    cfnType: 'AWS::EC2::Subnet',
    displayName: 'Subnet',
    friendlyName: 'Sub-Network',
    description: 'A range of IP addresses within your VPC. Can be public or private.',
    icon: '🔲',
    color: '#607d8b',
    bgColor: 'rgba(96,125,139,0.08)',
    category: 'Network',
    tags: ['network', 'subnet', 'networking', 'vpc'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_instance', relationship: 'subnet_id' },
      { targetResourceType: 'aws_db_instance', relationship: 'db_subnet_group_name' },
      { targetResourceType: 'aws_lambda_function', relationship: 'subnet_ids' },
    ],
    canReceiveFrom: ['aws_vpc'],
    secureDefaults: {
      map_public_ip_on_launch: false,
    },
    properties: [
      { key: 'cidr_block', label: 'CIDR Block', friendlyLabel: 'Address Range', type: 'cidr', required: true, default: '10.0.1.0/24', showInBeginner: true },
      { key: 'availability_zone', label: 'Availability Zone', friendlyLabel: 'Location', type: 'string', required: false, placeholder: 'us-east-1a' },
      { key: 'map_public_ip_on_launch', label: 'Auto-assign Public IP', friendlyLabel: 'Public Subnet', type: 'boolean', required: false, default: false },
    ],
  },

  // ─── Security Group ─────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_security_group',
    cfnType: 'AWS::EC2::SecurityGroup',
    displayName: 'Security Group',
    friendlyName: 'Firewall',
    description: 'Controls inbound and outbound traffic for your resources.',
    icon: '🛡️',
    color: '#f44336',
    bgColor: 'rgba(244,67,54,0.08)',
    category: 'Security',
    tags: ['security', 'firewall', 'network', 'security group', 'sg'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_instance', relationship: 'vpc_security_group_ids' },
      { targetResourceType: 'aws_db_instance', relationship: 'vpc_security_group_ids' },
      { targetResourceType: 'aws_alb', relationship: 'security_groups' },
    ],
    canReceiveFrom: ['aws_vpc'],
    secureDefaults: {
      ingress_cidr_blocks: [],
      egress_protocol: '-1',
    },
    properties: [
      { key: 'description', label: 'Description', friendlyLabel: 'What does this firewall do?', type: 'string', required: true, default: 'Managed by TerraBuilder', showInBeginner: true },
      { key: 'ingress_from_port', label: 'Inbound Port', friendlyLabel: 'Allow Inbound On Port', type: 'number', required: false, default: 443 },
      { key: 'ingress_to_port', label: 'Inbound To Port', friendlyLabel: 'Port Range End', type: 'number', required: false, default: 443 },
      { key: 'ingress_protocol', label: 'Inbound Protocol', friendlyLabel: 'Protocol', type: 'select', required: false, default: 'tcp', options: [
        { label: 'TCP', value: 'tcp' },
        { label: 'UDP', value: 'udp' },
        { label: 'All Traffic (-1)', value: '-1' },
      ]},
      { key: 'ingress_cidr_blocks', label: 'Allowed IP Ranges', friendlyLabel: 'Who Can Connect', type: 'string', required: false, default: '0.0.0.0/0', placeholder: '10.0.0.0/8' },
    ],
  },

  // ─── RDS Instance ──────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_db_instance',
    cfnType: 'AWS::RDS::DBInstance',
    displayName: 'RDS Database',
    friendlyName: 'Database',
    description: 'Managed relational database — PostgreSQL, MySQL, MariaDB, or Aurora.',
    icon: '🗄️',
    color: '#ff9800',
    bgColor: 'rgba(255,152,0,0.08)',
    category: 'Database',
    tags: ['database', 'rds', 'sql', 'postgres', 'mysql', 'relational'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_subnet', 'aws_security_group'],
    secureDefaults: {
      publicly_accessible: false,
      storage_encrypted: true,
      multi_az: true,
      backup_retention_period: 7,
      deletion_protection: true,
      auto_minor_version_upgrade: true,
    },
    properties: [
      { key: 'engine', label: 'Database Engine', friendlyLabel: 'Database Type', type: 'select', required: true, default: 'postgres', showInBeginner: true, options: [
        { label: 'PostgreSQL', value: 'postgres' },
        { label: 'MySQL', value: 'mysql' },
        { label: 'MariaDB', value: 'mariadb' },
        { label: 'SQL Server Express', value: 'sqlserver-ex' },
        { label: 'Oracle SE2', value: 'oracle-se2' },
      ]},
      { key: 'engine_version', label: 'Engine Version', friendlyLabel: 'Database Version', type: 'string', required: false, default: '15.4', placeholder: '15.4' },
      { key: 'instance_class', label: 'Instance Class', friendlyLabel: 'Database Size', type: 'select', required: true, default: 'db.t3.micro', showInBeginner: true, options: [
        { label: 'db.t3.micro — Dev/Test (Free Tier)', value: 'db.t3.micro' },
        { label: 'db.t3.small', value: 'db.t3.small' },
        { label: 'db.t3.medium', value: 'db.t3.medium' },
        { label: 'db.m5.large', value: 'db.m5.large' },
        { label: 'db.m5.xlarge', value: 'db.m5.xlarge' },
        { label: 'db.r5.large — Memory Optimized', value: 'db.r5.large' },
      ]},
      { key: 'db_name', label: 'Database Name', friendlyLabel: 'Database Name', type: 'string', required: false, default: 'appdb', showInBeginner: true },
      { key: 'username', label: 'Master Username', friendlyLabel: 'Admin Username', type: 'string', required: true, default: 'admin', showInBeginner: true },
      { key: 'password', label: 'Master Password', friendlyLabel: 'Admin Password', type: 'password', required: true, sensitiveValue: true, showInBeginner: true },
      { key: 'allocated_storage', label: 'Storage (GB)', friendlyLabel: 'Storage Space (GB)', type: 'number', required: true, default: 20, minValue: 20, maxValue: 65536 },
      { key: 'multi_az', label: 'Multi-AZ', friendlyLabel: 'High Availability', type: 'boolean', required: false, default: true, showInBeginner: true },
      { key: 'publicly_accessible', label: 'Publicly Accessible', friendlyLabel: 'Allow Public Access', type: 'boolean', required: false, default: false },
      { key: 'storage_encrypted', label: 'Encryption', friendlyLabel: 'Encrypt Data', type: 'boolean', required: false, default: true },
      { key: 'backup_retention_period', label: 'Backup Retention (days)', friendlyLabel: 'Keep Backups (days)', type: 'number', required: false, default: 7, minValue: 0, maxValue: 35 },
      { key: 'deletion_protection', label: 'Deletion Protection', friendlyLabel: 'Protect from Deletion', type: 'boolean', required: false, default: true },
    ],
  },

  // ─── Lambda Function ───────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_lambda_function',
    cfnType: 'AWS::Lambda::Function',
    displayName: 'Lambda Function',
    friendlyName: 'Serverless Function',
    description: 'Run code without managing servers. Pay only when code runs.',
    icon: '⚡',
    color: '#ff9800',
    bgColor: 'rgba(255,152,0,0.08)',
    category: 'Serverless',
    tags: ['serverless', 'lambda', 'function', 'faas', 'compute'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_iam_role', 'aws_subnet', 'aws_security_group', 'aws_sqs_queue', 'aws_api_gateway_rest_api'],
    secureDefaults: {
      reserved_concurrent_executions: -1,
    },
    properties: [
      { key: 'function_name', label: 'Function Name', friendlyLabel: 'Function Name', type: 'string', required: true, showInBeginner: true, placeholder: 'my-function' },
      { key: 'runtime', label: 'Runtime', friendlyLabel: 'Programming Language', type: 'select', required: true, default: 'nodejs20.x', showInBeginner: true, options: [
        { label: 'Node.js 20', value: 'nodejs20.x' },
        { label: 'Python 3.12', value: 'python3.12' },
        { label: 'Go 1.x', value: 'go1.x' },
        { label: 'Java 21', value: 'java21' },
        { label: 'Ruby 3.3', value: 'ruby3.3' },
        { label: '.NET 8', value: 'dotnet8' },
      ]},
      { key: 'handler', label: 'Handler', friendlyLabel: 'Entry Point', type: 'string', required: true, default: 'index.handler', placeholder: 'index.handler' },
      { key: 'timeout', label: 'Timeout (seconds)', friendlyLabel: 'Max Run Time (seconds)', type: 'number', required: false, default: 30, minValue: 1, maxValue: 900 },
      { key: 'memory_size', label: 'Memory (MB)', friendlyLabel: 'Memory Size (MB)', type: 'number', required: false, default: 128, minValue: 128, maxValue: 10240 },
    ],
  },

  // ─── DynamoDB Table ────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_dynamodb_table',
    cfnType: 'AWS::DynamoDB::Table',
    displayName: 'DynamoDB Table',
    friendlyName: 'NoSQL Database',
    description: 'Fast, serverless NoSQL database. No capacity management needed.',
    icon: '⚡',
    color: '#4caf50',
    bgColor: 'rgba(76,175,80,0.08)',
    category: 'Database',
    tags: ['nosql', 'dynamodb', 'database', 'serverless', 'key-value'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_lambda_function', 'aws_iam_role'],
    secureDefaults: {
      billing_mode: 'PAY_PER_REQUEST',
      server_side_encryption_enabled: true,
      point_in_time_recovery_enabled: true,
    },
    properties: [
      { key: 'name', label: 'Table Name', friendlyLabel: 'Table Name', type: 'string', required: true, showInBeginner: true, placeholder: 'my-table' },
      { key: 'billing_mode', label: 'Billing Mode', friendlyLabel: 'Pricing Model', type: 'select', required: false, default: 'PAY_PER_REQUEST', showInBeginner: true, options: [
        { label: 'On-Demand (Pay Per Request) — Recommended', value: 'PAY_PER_REQUEST' },
        { label: 'Provisioned (Set Capacity)', value: 'PROVISIONED' },
      ]},
      { key: 'hash_key', label: 'Partition Key', friendlyLabel: 'Unique ID Field', type: 'string', required: true, default: 'id', showInBeginner: true },
      { key: 'hash_key_type', label: 'Partition Key Type', friendlyLabel: 'ID Field Type', type: 'select', required: false, default: 'S', options: [
        { label: 'String (S)', value: 'S' },
        { label: 'Number (N)', value: 'N' },
        { label: 'Binary (B)', value: 'B' },
      ]},
      { key: 'server_side_encryption_enabled', label: 'Encryption at Rest', friendlyLabel: 'Encrypt Data', type: 'boolean', required: false, default: true },
      { key: 'point_in_time_recovery_enabled', label: 'Point-in-Time Recovery', friendlyLabel: 'Backup & Recovery', type: 'boolean', required: false, default: true },
    ],
  },

  // ─── ALB ───────────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_alb',
    cfnType: 'AWS::ElasticLoadBalancingV2::LoadBalancer',
    displayName: 'Application Load Balancer',
    friendlyName: 'Load Balancer',
    description: 'Distributes incoming traffic across multiple servers for reliability.',
    icon: '⚖️',
    color: '#3f51b5',
    bgColor: 'rgba(63,81,181,0.08)',
    category: 'Network',
    tags: ['load balancer', 'alb', 'traffic', 'network', 'ha'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_route53_record', relationship: 'alias_name' },
    ],
    canReceiveFrom: ['aws_security_group', 'aws_subnet'],
    secureDefaults: {
      internal: false,
      drop_invalid_header_fields: true,
      enable_deletion_protection: true,
    },
    properties: [
      { key: 'name', label: 'Load Balancer Name', friendlyLabel: 'Load Balancer Name', type: 'string', required: false, placeholder: 'my-alb' },
      { key: 'internal', label: 'Internal', friendlyLabel: 'Private (Internal Only)', type: 'boolean', required: false, default: false, showInBeginner: true },
      { key: 'enable_deletion_protection', label: 'Deletion Protection', friendlyLabel: 'Protect from Deletion', type: 'boolean', required: false, default: true },
      { key: 'drop_invalid_header_fields', label: 'Drop Invalid Headers', friendlyLabel: 'Block Invalid Requests', type: 'boolean', required: false, default: true },
    ],
  },

  // ─── IAM Role ──────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_iam_role',
    cfnType: 'AWS::IAM::Role',
    displayName: 'IAM Role',
    friendlyName: 'Permission Set',
    description: 'Permissions that AWS resources can assume. Controls what resources can do.',
    icon: '🔑',
    color: '#795548',
    bgColor: 'rgba(121,85,72,0.08)',
    category: 'IAM',
    tags: ['iam', 'role', 'permissions', 'security', 'identity'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_instance', relationship: 'iam_instance_profile' },
      { targetResourceType: 'aws_lambda_function', relationship: 'role' },
    ],
    canReceiveFrom: ['aws_iam_policy'],
    secureDefaults: {
      max_session_duration: 3600,
    },
    properties: [
      { key: 'name', label: 'Role Name', friendlyLabel: 'Permission Set Name', type: 'string', required: false, placeholder: 'my-role' },
      { key: 'assume_role_service', label: 'Trusted Service', friendlyLabel: 'Which Service Uses This', type: 'select', required: true, default: 'ec2.amazonaws.com', options: [
        { label: 'EC2 (Virtual Servers)', value: 'ec2.amazonaws.com' },
        { label: 'Lambda (Functions)', value: 'lambda.amazonaws.com' },
        { label: 'ECS (Containers)', value: 'ecs-tasks.amazonaws.com' },
        { label: 'EKS (Kubernetes)', value: 'eks.amazonaws.com' },
        { label: 'Glue (ETL)', value: 'glue.amazonaws.com' },
      ]},
      { key: 'max_session_duration', label: 'Max Session Duration (s)', friendlyLabel: 'Session Length (seconds)', type: 'number', required: false, default: 3600, minValue: 3600, maxValue: 43200 },
    ],
  },

  // ─── CloudFront Distribution ──────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_cloudfront_distribution',
    cfnType: 'AWS::CloudFront::Distribution',
    displayName: 'CloudFront CDN',
    friendlyName: 'Global CDN',
    description: 'Content Delivery Network. Serves files fast from 400+ global locations.',
    icon: '☁️',
    color: '#9c27b0',
    bgColor: 'rgba(156,39,176,0.08)',
    category: 'CDN & DNS',
    tags: ['cdn', 'cloudfront', 'cache', 'global', 'performance'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_s3_bucket', 'aws_alb'],
    secureDefaults: {
      default_cache_behavior_viewer_protocol_policy: 'redirect-to-https',
      minimum_protocol_version: 'TLSv1.2_2021',
      enabled: true,
    },
    properties: [
      { key: 'comment', label: 'Description', friendlyLabel: 'What is this CDN for?', type: 'string', required: false },
      { key: 'enabled', label: 'Enabled', friendlyLabel: 'Active', type: 'boolean', required: false, default: true },
      { key: 'default_cache_behavior_viewer_protocol_policy', label: 'HTTPS Policy', friendlyLabel: 'Force HTTPS', type: 'select', required: false, default: 'redirect-to-https', options: [
        { label: 'Redirect HTTP → HTTPS (Recommended)', value: 'redirect-to-https' },
        { label: 'HTTPS Only', value: 'https-only' },
        { label: 'Allow HTTP and HTTPS', value: 'allow-all' },
      ]},
      { key: 'price_class', label: 'Price Class', friendlyLabel: 'Coverage Area', type: 'select', required: false, default: 'PriceClass_100', options: [
        { label: 'North America + Europe (Cheapest)', value: 'PriceClass_100' },
        { label: 'Most Regions', value: 'PriceClass_200' },
        { label: 'All Regions (Most Expensive)', value: 'PriceClass_All' },
      ]},
    ],
  },

  // ─── Route53 Record ────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_route53_record',
    cfnType: 'AWS::Route53::RecordSet',
    displayName: 'Route53 DNS Record',
    friendlyName: 'Domain Name',
    description: 'DNS record to map your domain name to AWS resources.',
    icon: '🌍',
    color: '#00bcd4',
    bgColor: 'rgba(0,188,212,0.08)',
    category: 'CDN & DNS',
    tags: ['dns', 'route53', 'domain', 'routing'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_alb', 'aws_cloudfront_distribution'],
    secureDefaults: {},
    properties: [
      { key: 'name', label: 'Record Name', friendlyLabel: 'Domain Name', type: 'string', required: true, placeholder: 'app.example.com' },
      { key: 'type', label: 'Record Type', friendlyLabel: 'Record Type', type: 'select', required: true, default: 'A', options: [
        { label: 'A (IPv4 address)', value: 'A' },
        { label: 'CNAME (Alias to another domain)', value: 'CNAME' },
        { label: 'MX (Mail)', value: 'MX' },
        { label: 'TXT (Text)', value: 'TXT' },
      ]},
      { key: 'ttl', label: 'TTL (seconds)', friendlyLabel: 'Cache Duration (seconds)', type: 'number', required: false, default: 300 },
    ],
  },

  // ─── SQS Queue ─────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_sqs_queue',
    cfnType: 'AWS::SQS::Queue',
    displayName: 'SQS Queue',
    friendlyName: 'Message Queue',
    description: 'Decouple components with a managed message queue.',
    icon: '📨',
    color: '#ff5722',
    bgColor: 'rgba(255,87,34,0.08)',
    category: 'Messaging',
    tags: ['queue', 'sqs', 'messaging', 'async', 'event'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_lambda_function', relationship: 'event_source_arn' },
    ],
    canReceiveFrom: [],
    secureDefaults: {
      kms_master_key_id: 'alias/aws/sqs',
    },
    properties: [
      { key: 'name', label: 'Queue Name', friendlyLabel: 'Queue Name', type: 'string', required: false, placeholder: 'my-queue' },
      { key: 'delay_seconds', label: 'Delay (seconds)', friendlyLabel: 'Message Delay (seconds)', type: 'number', required: false, default: 0, minValue: 0, maxValue: 900 },
      { key: 'visibility_timeout_seconds', label: 'Visibility Timeout (s)', friendlyLabel: 'Processing Timeout (seconds)', type: 'number', required: false, default: 30, minValue: 0, maxValue: 43200 },
      { key: 'fifo_queue', label: 'FIFO Queue', friendlyLabel: 'Ordered Queue (FIFO)', type: 'boolean', required: false, default: false },
      { key: 'kms_master_key_id', label: 'KMS Key', friendlyLabel: 'Encryption Key', type: 'string', required: false, default: 'alias/aws/sqs' },
    ],
  },

  // ─── SNS Topic ─────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_sns_topic',
    cfnType: 'AWS::SNS::Topic',
    displayName: 'SNS Topic',
    friendlyName: 'Notification Service',
    description: 'Pub/sub messaging. Broadcast events to multiple subscribers.',
    icon: '🔔',
    color: '#e91e63',
    bgColor: 'rgba(233,30,99,0.08)',
    category: 'Messaging',
    tags: ['sns', 'notifications', 'pubsub', 'messaging', 'event'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_lambda_function'],
    secureDefaults: {
      kms_master_key_id: 'alias/aws/sns',
    },
    properties: [
      { key: 'name', label: 'Topic Name', friendlyLabel: 'Topic Name', type: 'string', required: false, placeholder: 'my-topic' },
      { key: 'display_name', label: 'Display Name', friendlyLabel: 'Display Name', type: 'string', required: false, placeholder: 'My Topic' },
      { key: 'fifo_topic', label: 'FIFO Topic', friendlyLabel: 'Ordered Topic (FIFO)', type: 'boolean', required: false, default: false },
      { key: 'kms_master_key_id', label: 'KMS Key', friendlyLabel: 'Encryption Key', type: 'string', required: false, default: 'alias/aws/sns' },
    ],
  },

  // ─── API Gateway ───────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_api_gateway_rest_api',
    cfnType: 'AWS::ApiGateway::RestApi',
    displayName: 'API Gateway',
    friendlyName: 'API Gateway',
    description: 'Create, publish, and secure APIs at any scale.',
    icon: '🔗',
    color: '#3f51b5',
    bgColor: 'rgba(63,81,181,0.08)',
    category: 'Serverless',
    tags: ['api', 'gateway', 'rest', 'http', 'serverless'],
    showInBeginner: true,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_lambda_function', relationship: 'integration_uri' },
    ],
    canReceiveFrom: [],
    secureDefaults: {},
    properties: [
      { key: 'name', label: 'API Name', friendlyLabel: 'API Name', type: 'string', required: true, placeholder: 'my-api', showInBeginner: true },
      { key: 'description', label: 'Description', friendlyLabel: 'What does this API do?', type: 'string', required: false },
      { key: 'endpoint_type', label: 'Endpoint Type', friendlyLabel: 'Access Type', type: 'select', required: false, default: 'REGIONAL', options: [
        { label: 'Regional (Same region)', value: 'REGIONAL' },
        { label: 'Edge Optimized (CloudFront)', value: 'EDGE' },
        { label: 'Private (VPC only)', value: 'PRIVATE' },
      ]},
    ],
  },

  // ─── ECS Cluster ───────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_ecs_cluster',
    cfnType: 'AWS::ECS::Cluster',
    displayName: 'ECS Cluster',
    friendlyName: 'Container Cluster',
    description: 'Run Docker containers at scale without managing servers.',
    icon: '🐳',
    color: '#1976d2',
    bgColor: 'rgba(25,118,210,0.08)',
    category: 'Container',
    tags: ['container', 'ecs', 'docker', 'fargate', 'cluster'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_subnet', 'aws_security_group'],
    secureDefaults: {
      containerInsights: 'enabled',
    },
    properties: [
      { key: 'name', label: 'Cluster Name', friendlyLabel: 'Cluster Name', type: 'string', required: true, placeholder: 'my-cluster' },
      { key: 'containerInsights', label: 'Container Insights', friendlyLabel: 'Enable Monitoring', type: 'select', required: false, default: 'enabled', options: [
        { label: 'Enabled (Recommended)', value: 'enabled' },
        { label: 'Disabled', value: 'disabled' },
      ]},
    ],
  },

  // ─── KMS Key ───────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_kms_key',
    cfnType: 'AWS::KMS::Key',
    displayName: 'KMS Key',
    friendlyName: 'Encryption Key',
    description: 'AWS managed encryption keys for securing data at rest.',
    icon: '🔐',
    color: '#607d8b',
    bgColor: 'rgba(96,125,139,0.08)',
    category: 'Security',
    tags: ['kms', 'encryption', 'key', 'security'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: [],
    secureDefaults: {
      enable_key_rotation: true,
      deletion_window_in_days: 30,
    },
    properties: [
      { key: 'description', label: 'Description', friendlyLabel: 'Key Description', type: 'string', required: false, placeholder: 'Encryption key for my-resource' },
      { key: 'enable_key_rotation', label: 'Key Rotation', friendlyLabel: 'Auto-Rotate Key Yearly', type: 'boolean', required: false, default: true },
      { key: 'deletion_window_in_days', label: 'Deletion Window (days)', friendlyLabel: 'Days Before Deletion', type: 'number', required: false, default: 30, minValue: 7, maxValue: 30 },
      { key: 'multi_region', label: 'Multi-Region', friendlyLabel: 'Multi-Region Key', type: 'boolean', required: false, default: false },
    ],
  },

  // ─── Secrets Manager ───────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_secretsmanager_secret',
    cfnType: 'AWS::SecretsManager::Secret',
    displayName: 'Secrets Manager',
    friendlyName: 'Secret Store',
    description: 'Securely store API keys, passwords, and credentials.',
    icon: '🔒',
    color: '#9c27b0',
    bgColor: 'rgba(156,39,176,0.08)',
    category: 'Security',
    tags: ['secrets', 'credentials', 'passwords', 'security', 'vault'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_kms_key'],
    secureDefaults: {},
    properties: [
      { key: 'name', label: 'Secret Name', friendlyLabel: 'Secret Name', type: 'string', required: true, placeholder: '/myapp/production/db-password' },
      { key: 'description', label: 'Description', friendlyLabel: 'What is this secret?', type: 'string', required: false },
      { key: 'recovery_window_in_days', label: 'Recovery Window (days)', friendlyLabel: 'Days to Recover After Deletion', type: 'number', required: false, default: 30, minValue: 7, maxValue: 30 },
    ],
  },

  // ─── CloudTrail ────────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_cloudtrail',
    cfnType: 'AWS::CloudTrail::Trail',
    displayName: 'CloudTrail',
    friendlyName: 'Audit Log',
    description: 'Log all API calls for compliance and security auditing.',
    icon: '📋',
    color: '#795548',
    bgColor: 'rgba(121,85,72,0.08)',
    category: 'Monitoring',
    tags: ['audit', 'cloudtrail', 'logging', 'compliance', 'governance'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_s3_bucket', relationship: 's3_bucket_name' },
    ],
    canReceiveFrom: [],
    secureDefaults: {
      is_multi_region_trail: true,
      enable_log_file_validation: true,
      include_global_service_events: true,
    },
    properties: [
      { key: 'name', label: 'Trail Name', friendlyLabel: 'Audit Log Name', type: 'string', required: true, placeholder: 'my-audit-trail' },
      { key: 'is_multi_region_trail', label: 'Multi-Region', friendlyLabel: 'Log All Regions', type: 'boolean', required: false, default: true },
      { key: 'enable_log_file_validation', label: 'Log Validation', friendlyLabel: 'Verify Log Integrity', type: 'boolean', required: false, default: true },
      { key: 'include_global_service_events', label: 'Global Events', friendlyLabel: 'Include Global Services', type: 'boolean', required: false, default: true },
    ],
  },

  // ─── CloudWatch Alarm ──────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_cloudwatch_metric_alarm',
    cfnType: 'AWS::CloudWatch::Alarm',
    displayName: 'CloudWatch Alarm',
    friendlyName: 'Alert',
    description: 'Monitor metrics and send alerts when thresholds are breached.',
    icon: '🔔',
    color: '#f44336',
    bgColor: 'rgba(244,67,54,0.08)',
    category: 'Monitoring',
    tags: ['monitoring', 'cloudwatch', 'alarm', 'alert', 'metrics'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: [],
    secureDefaults: {},
    properties: [
      { key: 'alarm_name', label: 'Alarm Name', friendlyLabel: 'Alert Name', type: 'string', required: true, placeholder: 'high-cpu-alarm' },
      { key: 'metric_name', label: 'Metric', friendlyLabel: 'What to Monitor', type: 'select', required: true, default: 'CPUUtilization', options: [
        { label: 'CPU Utilization', value: 'CPUUtilization' },
        { label: 'Memory Utilization', value: 'mem_used_percent' },
        { label: 'Network In', value: 'NetworkIn' },
        { label: 'Error Rate', value: 'Errors' },
      ]},
      { key: 'threshold', label: 'Threshold (%)', friendlyLabel: 'Alert When Above (%)', type: 'number', required: true, default: 80 },
      { key: 'comparison_operator', label: 'Operator', friendlyLabel: 'Condition', type: 'select', required: false, default: 'GreaterThanThreshold', options: [
        { label: 'Greater Than', value: 'GreaterThanThreshold' },
        { label: 'Less Than', value: 'LessThanThreshold' },
        { label: 'Greater Than or Equal', value: 'GreaterThanOrEqualToThreshold' },
      ]},
    ],
  },

  // ─── WAF Web ACL ───────────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_wafv2_web_acl',
    cfnType: 'AWS::WAFv2::WebACL',
    displayName: 'WAF Web ACL',
    friendlyName: 'Web Firewall',
    description: 'Protect web applications from common attacks like SQL injection and XSS.',
    icon: '🛡️',
    color: '#f44336',
    bgColor: 'rgba(244,67,54,0.08)',
    category: 'Security',
    tags: ['waf', 'firewall', 'security', 'protection', 'web'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [
      { targetResourceType: 'aws_alb', relationship: 'resource_arn' },
    ],
    canReceiveFrom: [],
    secureDefaults: {
      default_action: 'allow',
    },
    properties: [
      { key: 'name', label: 'Web ACL Name', friendlyLabel: 'Firewall Name', type: 'string', required: true, placeholder: 'my-web-acl' },
      { key: 'scope', label: 'Scope', friendlyLabel: 'Scope', type: 'select', required: true, default: 'REGIONAL', options: [
        { label: 'Regional (ALB, API GW)', value: 'REGIONAL' },
        { label: 'CloudFront', value: 'CLOUDFRONT' },
      ]},
      { key: 'default_action', label: 'Default Action', friendlyLabel: 'Default Action', type: 'select', required: false, default: 'allow', options: [
        { label: 'Allow (whitelist mode)', value: 'allow' },
        { label: 'Block (blacklist mode)', value: 'block' },
      ]},
    ],
  },

  // ─── Internet Gateway ──────────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_internet_gateway',
    cfnType: 'AWS::EC2::InternetGateway',
    displayName: 'Internet Gateway',
    friendlyName: 'Internet Access',
    description: 'Allows your VPC to communicate with the internet.',
    icon: '🌐',
    color: '#00bcd4',
    bgColor: 'rgba(0,188,212,0.08)',
    category: 'Network',
    tags: ['network', 'internet', 'gateway', 'routing'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_vpc'],
    secureDefaults: {},
    properties: [
      { key: 'tags_Name', label: 'Name', friendlyLabel: 'Gateway Name', type: 'string', required: false, placeholder: 'main-igw' },
    ],
  },

  // ─── ElastiCache (Redis) ───────────────────────────────────────────────
  {
    provider: 'aws',
    resourceType: 'aws_elasticache_replication_group',
    cfnType: 'AWS::ElastiCache::ReplicationGroup',
    displayName: 'ElastiCache (Redis)',
    friendlyName: 'Cache',
    description: 'In-memory caching with Redis. Speeds up apps dramatically.',
    icon: '🚀',
    color: '#ff5722',
    bgColor: 'rgba(255,87,34,0.08)',
    category: 'Database',
    tags: ['cache', 'redis', 'elasticache', 'performance', 'in-memory'],
    showInBeginner: false,
    showInIntermediate: true,
    canConnectTo: [],
    canReceiveFrom: ['aws_subnet', 'aws_security_group'],
    secureDefaults: {
      at_rest_encryption_enabled: true,
      transit_encryption_enabled: true,
      multi_az_enabled: true,
      automatic_failover_enabled: true,
    },
    properties: [
      { key: 'replication_group_id', label: 'Replication Group ID', friendlyLabel: 'Cache Name', type: 'string', required: true, placeholder: 'my-redis' },
      { key: 'node_type', label: 'Node Type', friendlyLabel: 'Cache Size', type: 'select', required: true, default: 'cache.t3.micro', options: [
        { label: 'cache.t3.micro (Dev)', value: 'cache.t3.micro' },
        { label: 'cache.t3.small', value: 'cache.t3.small' },
        { label: 'cache.m5.large', value: 'cache.m5.large' },
        { label: 'cache.r6g.large (Memory Optimized)', value: 'cache.r6g.large' },
      ]},
      { key: 'num_cache_clusters', label: 'Number of Nodes', friendlyLabel: 'Number of Nodes', type: 'number', required: false, default: 2, minValue: 1, maxValue: 6 },
      { key: 'at_rest_encryption_enabled', label: 'Encryption at Rest', friendlyLabel: 'Encrypt Data', type: 'boolean', required: false, default: true },
      { key: 'transit_encryption_enabled', label: 'Encryption in Transit', friendlyLabel: 'Encrypt Network Traffic', type: 'boolean', required: false, default: true },
    ],
  },
];
